import React, { useEffect, useMemo, useState } from 'react';
import axios from 'axios';

const featureConfigs = {
  'plan-spec-upload': {
    title: 'Plan & Spec Upload',
    icon: '\ud83d\udcc4',
    description: 'Drawing, specification, addendum, and bid instruction extraction.',
    columns: [
      ['upload_name', 'Upload'],
      ['project_name', 'Project'],
      ['document_type', 'Type'],
      ['uploaded_by', 'Uploaded By'],
      ['status', 'Status', 'badge'],
      ['spec_count', 'Specs'],
      ['extraction_count', 'Extractions'],
    ],
    search: ['upload_name', 'project_name', 'document_type', 'uploaded_by', 'status'],
  },
  'bid-risk-analysis': {
    title: 'Bid Risk Analysis',
    icon: '\u26a0\ufe0f',
    description: 'Structured findings for missing scope, ambiguous terms, schedule exposure, and cost risk.',
    columns: [
      ['project_name', 'Project'],
      ['contractor_name', 'Bidder'],
      ['bid_amount', 'Bid Amount', 'money'],
      ['overall_score', 'Risk Score', 'score'],
      ['status', 'Status', 'badge'],
      ['finding_count', 'Findings'],
    ],
    search: ['project_name', 'contractor_name', 'status', 'summary'],
  },
  'cost-estimate-review': {
    title: 'Cost Estimate Review',
    icon: '\ud83d\udcb5',
    description: 'Estimate review against historical costs, material quotes, labor assumptions, and contingency.',
    columns: [
      ['project_name', 'Project'],
      ['category', 'Category'],
      ['estimated_amount', 'Estimate', 'money'],
      ['variance_score', 'Variance Score', 'score'],
      ['status', 'Status', 'badge'],
      ['variance_count', 'Variances'],
    ],
    search: ['project_name', 'category', 'reviewer', 'status', 'summary'],
  },
  'permit-checklists': {
    title: 'Permit Checklists',
    icon: '\ud83c\udfdb\ufe0f',
    description: 'Permit requirements by jurisdiction, trade, phase, and authority.',
    columns: [
      ['project_name', 'Project'],
      ['jurisdiction', 'Jurisdiction'],
      ['trade', 'Trade'],
      ['phase', 'Phase'],
      ['due_date', 'Due', 'date'],
      ['status', 'Status', 'badge'],
    ],
    search: ['project_name', 'jurisdiction', 'trade', 'phase', 'status', 'owner'],
  },
  'safety-plans': {
    title: 'Safety Plans',
    icon: '\ud83e\uddba',
    description: 'Safety plans, hazard controls, toolbox talks, and inspection follow-up.',
    columns: [
      ['plan_name', 'Plan'],
      ['project_name', 'Project'],
      ['generated_by', 'Generated By'],
      ['status', 'Status', 'badge'],
      ['hazard_count', 'Hazards'],
      ['inspection_count', 'Inspections'],
    ],
    search: ['plan_name', 'project_name', 'generated_by', 'status', 'summary'],
  },
  'subcontractor-scoring': {
    title: 'Subcontractor Scoring',
    icon: '\ud83d\udee0\ufe0f',
    description: 'Data-backed comparison by availability, insurance, performance, safety, and scope fit.',
    columns: [
      ['company_name', 'Subcontractor'],
      ['specialty', 'Specialty'],
      ['project_name', 'Project'],
      ['overall_score', 'Overall', 'score'],
      ['scope_fit_score', 'Scope Fit', 'score'],
      ['status', 'Status', 'badge'],
    ],
    search: ['company_name', 'specialty', 'project_name', 'status'],
  },
  'change-order-impacts': {
    title: 'Change Order Impacts',
    icon: '\ud83d\udcdd',
    description: 'Change order cost impact, schedule impact, source document, risk, and approval state.',
    columns: [
      ['change_order_title', 'Change Order'],
      ['project_name', 'Project'],
      ['cost_impact', 'Cost Impact', 'money'],
      ['schedule_impact_days', 'Days'],
      ['risk_level', 'Risk', 'badge'],
      ['status', 'Status', 'badge'],
    ],
    search: ['change_order_title', 'project_name', 'risk_level', 'status', 'owner', 'summary'],
  },
  'project-risk-dashboard': {
    title: 'Project Risk Dashboard',
    icon: '\ud83d\udcca',
    description: 'Computed risk metrics for bid margin, permit blockers, safety exposure, subcontractor risk, and open change impacts.',
    columns: [
      ['project_name', 'Project'],
      ['project_status', 'Status', 'badge'],
      ['risk_score', 'Risk Score', 'score'],
      ['high_risk_items', 'Risks'],
      ['permit_blockers', 'Permit Blockers'],
      ['safety_exposures', 'Safety'],
      ['open_change_impacts', 'Open CO'],
      ['subcontractor_score', 'Sub Score', 'score'],
    ],
    search: ['project_name', 'project_status'],
  },
};

const childLabels = {
  spec_documents: 'Spec Documents',
  document_extractions: 'Document Extractions',
  risk_findings: 'Risk Findings',
  estimate_variances: 'Estimate Variances',
  permit_requirements: 'Permit Requirements',
  status_events: 'Status Events',
  hazards: 'Hazards',
  inspections: 'Inspections',
  evaluations: 'Evaluations',
  approvals: 'Approvals',
  bid_readiness: 'Bid Readiness',
};

const hiddenDetailKeys = new Set(['children']);

const formatDate = (value) => value ? new Date(value).toLocaleDateString() : 'N/A';
const formatDateTime = (value) => value ? new Date(value).toLocaleString() : 'N/A';
const formatMoney = (value) => value || Number(value) === 0 ? `$${Number(value).toLocaleString()}` : 'N/A';

const humanize = (value) => String(value || '').replace(/_/g, ' ');

const formatCell = (value, type) => {
  if (type === 'date') return formatDate(value);
  if (type === 'datetime') return formatDateTime(value);
  if (type === 'money') return formatMoney(value);
  if (type === 'score') return <strong>{value || Number(value) === 0 ? value : 'N/A'}</strong>;
  if (type === 'badge') return <span className={`badge badge-${String(value || 'pending').replace(/_/g, '-')}`}>{humanize(value || 'N/A')}</span>;
  return value || 'N/A';
};

const renderValue = (key, value) => {
  if (key.includes('amount') || (key.includes('impact') && key.includes('cost'))) return formatMoney(value);
  if (key.includes('date') || key.includes('created_at') || key.includes('updated_at')) return formatDateTime(value);
  if (key.includes('status') || key.includes('severity') || key.includes('risk_level')) {
    return <span className={`badge badge-${String(value || 'pending').replace(/_/g, '-')}`}>{humanize(value || 'N/A')}</span>;
  }
  return String(value ?? 'N/A');
};

const ExpansionFeaturePage = ({ feature }) => {
  const config = featureConfigs[feature];
  const [items, setItems] = useState([]);
  const [selectedItem, setSelectedItem] = useState(null);
  const [detail, setDetail] = useState(null);
  const [searchTerm, setSearchTerm] = useState('');
  const [loading, setLoading] = useState(true);
  const [toast, setToast] = useState(null);

  useEffect(() => {
    const load = async () => {
      setLoading(true);
      try {
        const res = await axios.get(`/api/feature-expansion/${feature}`);
        setItems(res.data);
      } catch {
        setToast({ type: 'error', message: `Failed to fetch ${config.title.toLowerCase()}` });
      } finally {
        setLoading(false);
      }
    };
    load();
  }, [feature, config.title]);

  const filtered = useMemo(() => {
    const term = searchTerm.toLowerCase();
    if (!term) return items;
    return items.filter((item) => config.search.some((field) => String(item[field] || '').toLowerCase().includes(term)));
  }, [items, searchTerm, config.search]);

  const openDetail = async (item) => {
    setSelectedItem(item);
    try {
      const id = feature === 'project-risk-dashboard' ? item.project_id : item.id;
      const res = await axios.get(`/api/feature-expansion/${feature}/${id}`);
      setDetail(res.data);
    } catch {
      setDetail(item);
      setToast({ type: 'error', message: 'Could not load detail records.' });
    }
  };

  if (!config) return null;

  if (loading) {
    return <div className="loading-container"><div className="spinner"></div><p className="loading-text">Loading {config.title.toLowerCase()}...</p></div>;
  }

  return (
    <div>
      {toast && (
        <div className="toast-container">
          <div className={`toast toast-${toast.type}`}>
            <span>{toast.type === 'success' ? '\u2705' : '\u274c'}</span>
            {toast.message}
            <button className="toast-close" onClick={() => setToast(null)}>&times;</button>
          </div>
        </div>
      )}

      <div className="page-header expansion-header">
        <div>
          <h1>{config.icon} {config.title}</h1>
          <p>{config.description}</p>
        </div>
        <div className="header-actions">
          <div className="search-box">
            <input value={searchTerm} onChange={(e) => setSearchTerm(e.target.value)} placeholder={`Search ${config.title.toLowerCase()}...`} />
          </div>
        </div>
      </div>

      <div className="table-container">
        <table className="data-table">
          <thead>
            <tr>{config.columns.map(([, label]) => <th key={label}>{label}</th>)}</tr>
          </thead>
          <tbody>
            {filtered.length === 0 ? (
              <tr><td colSpan={config.columns.length}><div className="table-empty"><span className="empty-icon">{config.icon}</span><p>No records found</p></div></td></tr>
            ) : filtered.map((item) => (
              <tr key={`${feature}-${item.id || item.project_id}`} onClick={() => openDetail(item)}>
                {config.columns.map(([key, , type]) => <td key={key}>{formatCell(item[key], type)}</td>)}
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {selectedItem && detail && (
        <div className="modal-overlay" onClick={() => { setSelectedItem(null); setDetail(null); }}>
          <div className="modal modal-wide" onClick={(e) => e.stopPropagation()}>
            <div className="modal-header">
              <h2>{detail.upload_name || detail.project_name || detail.plan_name || detail.change_order_title || config.title}</h2>
              <button className="modal-close" onClick={() => { setSelectedItem(null); setDetail(null); }}>&times;</button>
            </div>
            <div className="modal-body">
              <div className="detail-grid">
                {Object.entries(detail).filter(([key]) => !hiddenDetailKeys.has(key)).map(([key, value]) => (
                  <div className={String(value || '').length > 90 ? 'detail-item full-width' : 'detail-item'} key={key}>
                    <div className="detail-label">{humanize(key)}</div>
                    <div className="detail-value">{renderValue(key, value)}</div>
                  </div>
                ))}
              </div>

              {Object.entries(detail.children || {}).map(([key, rows]) => (
                <div className="child-section" key={key}>
                  <h3>{childLabels[key] || humanize(key)}</h3>
                  {rows.length === 0 ? (
                    <p className="muted-text">No related records.</p>
                  ) : (
                    <div className="child-grid">
                      {rows.map((row) => (
                        <div className="child-card" key={`${key}-${row.id || row.bid_id}`}>
                          {Object.entries(row).filter(([rowKey]) => !rowKey.endsWith('_id') && rowKey !== 'id').map(([rowKey, rowValue]) => (
                            <div key={rowKey}>
                              <span>{humanize(rowKey)}</span>
                              <strong>{renderValue(rowKey, rowValue)}</strong>
                            </div>
                          ))}
                        </div>
                      ))}
                    </div>
                  )}
                </div>
              ))}
            </div>
            <div className="modal-footer">
              <button className="btn btn-outline" onClick={() => { setSelectedItem(null); setDetail(null); }}>Close</button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default ExpansionFeaturePage;
