BEGIN;
CREATE TABLE IF NOT EXISTS cb_organizations (id BIGSERIAL PRIMARY KEY, tenant_key TEXT NOT NULL UNIQUE, name TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS cb_memberships (organization_id BIGINT NOT NULL REFERENCES cb_organizations(id), user_id BIGINT NOT NULL, role TEXT NOT NULL CHECK(role IN ('viewer','estimator','manager','admin')), PRIMARY KEY(organization_id,user_id));
CREATE TABLE IF NOT EXISTS cb_packages (
 id BIGSERIAL PRIMARY KEY, organization_id BIGINT NOT NULL REFERENCES cb_organizations(id), project_id BIGINT, name TEXT NOT NULL,
 status TEXT NOT NULL DEFAULT 'draft' CHECK(status IN ('draft','review','approved','issued','closed')), version INTEGER NOT NULL DEFAULT 1,
 due_at TIMESTAMPTZ, created_by BIGINT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS cb_documents (id BIGSERIAL PRIMARY KEY, package_id BIGINT NOT NULL REFERENCES cb_packages(id), kind TEXT NOT NULL CHECK(kind IN ('plan','specification','addendum','bid')), revision TEXT NOT NULL, storage_key TEXT NOT NULL, sha256 TEXT NOT NULL, supersedes_id BIGINT REFERENCES cb_documents(id), uploaded_by BIGINT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE(package_id,kind,revision,sha256));
CREATE TABLE IF NOT EXISTS cb_scope_items (id BIGSERIAL PRIMARY KEY, package_id BIGINT NOT NULL REFERENCES cb_packages(id), code TEXT NOT NULL, description TEXT NOT NULL, quantity NUMERIC(14,4) NOT NULL CHECK(quantity >= 0), unit TEXT NOT NULL, source_document_id BIGINT REFERENCES cb_documents(id), source_locator TEXT, UNIQUE(package_id,code));
CREATE TABLE IF NOT EXISTS cb_bid_submissions (id BIGSERIAL PRIMARY KEY, package_id BIGINT NOT NULL REFERENCES cb_packages(id), bidder_id BIGINT NOT NULL, status TEXT NOT NULL DEFAULT 'received' CHECK(status IN ('received','normalized','review','approved','rejected')), submitted_at TIMESTAMPTZ NOT NULL, currency CHAR(3) NOT NULL, total NUMERIC(16,2) CHECK(total >= 0), version INTEGER NOT NULL DEFAULT 1, UNIQUE(package_id,bidder_id));
CREATE TABLE IF NOT EXISTS cb_bid_lines (id BIGSERIAL PRIMARY KEY, submission_id BIGINT NOT NULL REFERENCES cb_bid_submissions(id), scope_code TEXT NOT NULL, quantity NUMERIC(14,4), unit TEXT, unit_price NUMERIC(16,4), inclusion_status TEXT NOT NULL CHECK(inclusion_status IN ('included','excluded','allowance','unclear')), notes TEXT, UNIQUE(submission_id,scope_code));
CREATE TABLE IF NOT EXISTS cb_risks (id BIGSERIAL PRIMARY KEY, submission_id BIGINT NOT NULL REFERENCES cb_bid_submissions(id), kind TEXT NOT NULL, severity TEXT NOT NULL CHECK(severity IN ('low','medium','high','critical')), evidence JSONB NOT NULL, status TEXT NOT NULL DEFAULT 'open' CHECK(status IN ('open','mitigated','accepted')), owner_id BIGINT);
CREATE TABLE IF NOT EXISTS cb_decisions (id BIGSERIAL PRIMARY KEY, submission_id BIGINT NOT NULL REFERENCES cb_bid_submissions(id), decision TEXT NOT NULL CHECK(decision IN ('request_clarification','shortlist','approve','reject')), rationale TEXT NOT NULL, decided_by BIGINT NOT NULL, decided_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS cb_audit_events (id BIGSERIAL PRIMARY KEY, organization_id BIGINT, actor_id BIGINT, action TEXT NOT NULL, entity_type TEXT NOT NULL, entity_id BIGINT, before_state JSONB, after_state JSONB, occurred_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS cb_connector_runs (id BIGSERIAL PRIMARY KEY, organization_id BIGINT NOT NULL, connector TEXT NOT NULL, idempotency_key TEXT NOT NULL, status TEXT NOT NULL CHECK(status IN ('running','succeeded','failed','blocked')), failure JSONB, started_at TIMESTAMPTZ NOT NULL DEFAULT now(), finished_at TIMESTAMPTZ, UNIQUE(organization_id,connector,idempotency_key));
COMMIT;
